name: Docs Preview

on:
  pull_request:
  push:
    branches-ignore: [ main ]

permissions:
  contents: read

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies (with docs)
        run: poetry install --with docs

      - name: Generate API
        run: poetry run python docs/source/generate_api.py

      - name: Generate User Guide
        run: poetry run python docs/source/generate_user_guide.py

      - name: Build docs (Sphinx)
        run: |
          poetry run sphinx-build -E -a -b html docs/source docs/build/html
          touch docs/build/html/.nojekyll

      - name: Upload docs preview artifact
        uses: actions/upload-artifact@v7
        with:
          name: docs-html-preview
          path: docs/build/html
          retention-days: 7
