name: Docs Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies (with docs)
        run: poetry install --with docs

      - name: Generate API
        run: poetry run python docs/source/generate_api.py

      - name: Generate User Guide
        run: poetry run python docs/source/generate_user_guide.py

      - name: Build docs (Sphinx)
        run: |
          poetry run sphinx-build -E -a -b html docs/source docs/build/html
          touch docs/build/html/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/build/html

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
